version: "3.8"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=12345678

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80" 

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=jobby
      - PGHOST=jobby.czkaa4kseikm.us-east-1.rds.amazonaws.com
      - PGDATABASE=postgres
      - PGPASSWORD=12345678
      - PGPORT=5432

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
