version: '3.8'

services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: jobhub-client
    networks:
      - app-network

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: jobhub-server
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: "jobby"
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_DB: "postgres"
      POSTGRES_HOST: "jobby.czkaa4kseikm.us-east-1.rds.amazonaws.com"
      POSTGRES_PORT: "5432"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: jobhub-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./Client/build:/usr/share/nginx/html  # Serve the React build output
    depends_on:
      - client
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
